##Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

##1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

##By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

a = []

def fibonacci(n):
    if n == 1:
        return 1
    if n == 2:
        return 2
    return (fibonacci(n-1)+fibonacci(n-2))

def guardar_lista(n):
    for i in range(1,n):
        a.append(fibonacci(i))
    return a

##indice = 1
## n = 0
##while(n <= 4000000):
##    indice = indice + 1
##    n = fibonacci(indice)
##
##print(indice)

def filtrar_pares(lista):
    b = []
    for elem in lista:
        if elem % 2 == 0:
            b.append(elem)
    return b
    

listado_de_fibonacci = filtrar_pares(guardar_lista(33))
print(listado_de_fibonacci)
print(sum(listado_de_fibonacci))
