'''
Triangular, pentagonal, and hexagonal
Problem 45 
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''

def triangle_number(n):
    return n*(n+1)/2

def pentagonal_number(n):
    return n*(3*n-1)/2

def hexagonal_number(n):
    return n*(2*n-1)

t = 286
p = 166
h = 144

def problema():
    t = 286
    p = 166
    h = 144
    while(triangle_number(t) != pentagonal_number(p) or 
          triangle_number(t) != hexagonal_number(h)):
        
        if triangle_number(t) > pentagonal_number(p):
            p += 1
        if triangle_number(t) > hexagonal_number(h):
            h += 1
        
        t += 1
    
    return triangle_number(t)

print(problema())


